// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB01OC2qik3XFwMAHClnF7UgAn_u3-wOMA',
    appId: '1:216987623645:web:cc52fc4186ed5ae7f1bb34',
    messagingSenderId: '216987623645',
    projectId: 'hukum2-67bb8',
    authDomain: 'hukum2-67bb8.firebaseapp.com',
    databaseURL: 'https://hukum2-67bb8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hukum2-67bb8.appspot.com',
    measurementId: 'G-MRN1FSZZTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZpU4MZw35vPAP4VkN1INKdehLePcxp0A',
    appId: '1:216987623645:android:330991e41cef479df1bb34',
    messagingSenderId: '216987623645',
    projectId: 'hukum2-67bb8',
    databaseURL: 'https://hukum2-67bb8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hukum2-67bb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBolB9j8o7T_kYLwKL-qiDegTU0TrNfyQ8',
    appId: '1:216987623645:ios:a056125714d2057bf1bb34',
    messagingSenderId: '216987623645',
    projectId: 'hukum2-67bb8',
    databaseURL: 'https://hukum2-67bb8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hukum2-67bb8.appspot.com',
    iosBundleId: 'com.example.demoLibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBolB9j8o7T_kYLwKL-qiDegTU0TrNfyQ8',
    appId: '1:216987623645:ios:55a7083595fd585ef1bb34',
    messagingSenderId: '216987623645',
    projectId: 'hukum2-67bb8',
    databaseURL: 'https://hukum2-67bb8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hukum2-67bb8.appspot.com',
    iosBundleId: 'com.example.demoLibrary.RunnerTests',
  );
}
